Bump to Akka 2.6.10
Currently we're getting warnings in CI running the pipeline_storage
tests:

    java.lang.IllegalStateException: You are using version 2.6.10 of
    Akka, but it appears you (perhaps indirectly) also depend on older
    versions of related artifacts. You can solve this by adding an
    explicit dependency on version 2.6.10 of the [akka-slf4j,
    akka-protobuf-v3, akka-stream] artifacts to your project.
    See also: https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed